######################################################################
# Automatically generated by qmake (3.0) Sat Oct 9 09:42:51 2021
######################################################################

TEMPLATE = app
TARGET = qtproject
INCLUDEPATH += .

QT += gui widgets

# Input
SOURCES += testmain.cpp
